import { Package, Journey } from './types';

export const packages: Package[] = [
    /* ════════════════════════════════════════
       LUXURY
       ════════════════════════════════════════ */
    {
        id: '1',
        slug: 'azure-atoll-escape',
        category: 'luxury',
        title: 'Azure Atoll Escape',

        location: 'Maldives',
        days: 5,
        image_url: '/images/maldives-beach.jpg',
        tag: 'Luxury',
        highlights: ['Overwater Villa', 'Seaplane Transfer', 'Private Dining'],
        description: 'Surrender to the unparalleled luxury of the Maldivian atolls. Your private overwater villa awaits above crystal-clear lagoons, where dolphin pods play at dawn and bioluminescent plankton illuminate the night.',
        itinerary: [
            { day: 1, title: 'Seaplane to Paradise', description: 'Arrive at Velana International Airport. Board a scenic seaplane to your private atoll resort. Welcome with champagne on the jetty of your overwater villa.', highlights: ['Seaplane transfer', 'Overwater villa check-in', 'Champagne welcome'] },
            { day: 2, title: 'Ocean Discovery', description: 'Guided snorkeling at the house reef. Afternoon private catamaran cruise with dolphin spotting. Sunset dining on a private sandbank.', highlights: ['House reef snorkeling', 'Dolphin cruise', 'Sandbank dinner'] },
            { day: 3, title: 'Underwater Wonders', description: 'Visit the resort\'s marine biology center. Guided diving excursion to a pristine coral wall. Evening underwater restaurant experience.', highlights: ['Marine biology tour', 'Coral wall diving', 'Underwater dining'] },
            { day: 4, title: 'Spa & Serenity', description: 'Full-day overwater spa journey. Traditional Maldivian healing ritual. Private yoga session at sunrise. Bioluminescent beach walk at night.', highlights: ['Overwater spa treatment', 'Sunrise yoga', 'Bioluminescent beach'] },
            { day: 5, title: 'Fond Farewell', description: 'Final sunrise from your villa deck. Gourmet farewell breakfast. Seaplane transfer back to Malé with lasting memories of paradise.', highlights: ['Villa sunrise', 'Farewell breakfast', 'Seaplane departure'] },
        ],
    },
    {
        id: '2',
        slug: 'the-dual-paradise',
        category: 'luxury',
        title: 'The Dual Paradise',
        location: 'Sri Lanka & Maldives',
        days: 14,
        image_url: '/images/luxury-hero.jpg',
        tag: 'Signature',
        highlights: ['Two Destinations', 'Heritage & Beach', 'Overwater Spa'],
        description: 'The ultimate journey combining the cultural richness of Sri Lanka with the pristine luxury of the Maldives. Seven days immersed in ancient temples, misty mountains, and wildlife safaris, followed by seven days of overwater bliss.',
        itinerary: [
            { day: 1, title: 'Colombo Arrival', description: 'Welcome to Sri Lanka. VIP airport pickup and transfer to your boutique heritage hotel. Evening Colombo food tour.', highlights: ['VIP airport transfer', 'Heritage hotel', 'Colombo food tour'] },
            { day: 2, title: 'Cultural Triangle', description: 'Journey to Sigiriya. Visit Dambulla Golden Temple. Check in to your private villa overlooking the ancient rock fortress.', highlights: ['Dambulla Golden Temple', 'Private villa', 'Sigiriya views'] },
            { day: 3, title: 'Sigiriya & Safari', description: 'Early climb of Sigiriya Rock. Afternoon jeep safari at Minneriya National Park for the elephant gathering.', highlights: ['Sigiriya Rock climb', 'Minneriya safari', 'Elephant gathering'] },
            { day: 4, title: 'Kandy Heritage', description: 'Travel to Kandy through spice gardens. Visit Temple of the Tooth. Private Kandyan dance performance.', highlights: ['Spice gardens', 'Temple of the Tooth', 'Dance performance'] },
            { day: 5, title: 'Tea Plantations', description: 'Full-day tea country exploration. Visit Ceylon Tea Museum. Private estate lunch in the highlands.', highlights: ['Tea Museum', 'Plantation walk', 'Highland lunch'] },
            { day: 6, title: 'Ella & Nine Arches', description: 'Scenic train ride to Ella. Visit the iconic Nine Arches Bridge. Ella Rock sunset hike.', highlights: ['Scenic train ride', 'Nine Arches Bridge', 'Sunset hike'] },
            { day: 7, title: 'Southern Coast', description: 'Travel to the southern coast. Visit Galle Fort. Sunset whale watching excursion off Mirissa.', highlights: ['Galle Fort', 'Beach resort', 'Whale watching'] },
            { day: 8, title: 'Fly to Maldives', description: 'Morning flight from Colombo to Malé. Seaplane transfer to your luxury overwater villa. Welcome ceremony.', highlights: ['Flight to Malé', 'Seaplane transfer', 'Overwater villa'] },
            { day: 9, title: 'Reef Discovery', description: 'Guided house reef snorkeling with marine biologist. Afternoon spa treatment. Private beach cinema under the stars.', highlights: ['Reef snorkeling', 'Spa treatment', 'Beach cinema'] },
            { day: 10, title: 'Deep Blue Adventure', description: 'Half-day diving expedition to Manta Ray Point. Jet ski excursion. Floating breakfast in your villa.', highlights: ['Manta ray diving', 'Jet skiing', 'Floating breakfast'] },
            { day: 11, title: 'Island Exploration', description: 'Private yacht trip to uninhabited islands. Picnic lunch on a pristine sandbar. Sunset fishing with local fishermen.', highlights: ['Private yacht', 'Sandbar picnic', 'Sunset fishing'] },
            { day: 12, title: 'Wellness Day', description: 'Full-day Maldivian wellness journey. Overwater spa rituals. Sunrise yoga and meditation. Star-gazing dinner.', highlights: ['Wellness rituals', 'Yoga & meditation', 'Star-gazing dinner'] },
            { day: 13, title: 'Ocean Freedom', description: 'Free day to explore at your leisure. Parasailing, paddleboarding, or simply relax. Chef\'s farewell dinner.', highlights: ['Water sports', 'Relaxation', 'Chef\'s farewell dinner'] },
            { day: 14, title: 'Paradise Farewell', description: 'Final sunrise meditation. Farewell brunch overlooking the lagoon. Seaplane transfer and departure.', highlights: ['Sunrise meditation', 'Farewell brunch', 'Seaplane departure'] },
        ],
    },
    {
        id: '3',
        slug: 'golden-coast-retreat',
        category: 'luxury',
        title: 'Golden Coast Retreat',
        location: 'Sri Lanka',
        days: 7,
        image_url: '/images/wellness-hero.jpg',
        tag: 'Premium',
        highlights: ['Boutique Hotels', 'Galle Fort', 'Private Chef'],
        description: 'Experience Sri Lanka\'s stunning southern coastline from handpicked boutique hotels. Explore the colonial charm of Galle Fort, surf pristine waves, and dine with a private chef on moonlit beaches.',
        itinerary: [
            { day: 1, title: 'Welcome to the Coast', description: 'Arrive in Colombo and transfer to your beachfront boutique hotel on the southern coast.', highlights: ['Airport transfer', 'Beachfront check-in', 'Welcome cocktail'] },
            { day: 2, title: 'Galle Fort Exploration', description: 'Private guided tour of the UNESCO-listed Galle Fort. Artisan shopping and colonial architecture.', highlights: ['Galle Fort tour', 'Artisan boutiques', 'Fort rooftop dining'] },
            { day: 3, title: 'Whale Watching', description: 'Early morning whale watching expedition off Mirissa. Afternoon at leisure on the beach.', highlights: ['Blue whale spotting', 'Beach relaxation', 'Seafood dinner'] },
            { day: 4, title: 'Surfing & Beach Life', description: 'Morning surf lesson at Weligama Bay. Afternoon spa treatment. Private beach dinner.', highlights: ['Surf lesson', 'Spa treatment', 'Beach dinner'] },
            { day: 5, title: 'Tea Country Day Trip', description: 'Scenic drive through tea plantations. Visit a boutique tea estate. Afternoon tea tasting.', highlights: ['Tea plantations', 'Estate visit', 'Tea tasting'] },
            { day: 6, title: 'Jungle & Lagoon', description: 'Kayak through mangrove lagoons. Visit a turtle hatchery. Evening private chef dinner.', highlights: ['Mangrove kayaking', 'Turtle hatchery', 'Private chef'] },
            { day: 7, title: 'Departure', description: 'Final morning yoga on the beach. Transfer to Colombo airport.', highlights: ['Beach yoga', 'Airport transfer', 'Farewell gift'] },
        ],
    },

    /* ════════════════════════════════════════
       HONEYMOON
       ════════════════════════════════════════ */
    {
        id: '4',
        slug: 'island-romance',
        category: 'honeymoon',
        title: 'Island Romance',
        location: 'Maldives',
        days: 7,
        image_url: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1200&q=80',
        tag: 'Romance',
        highlights: ['Overwater Villa', 'Sunset Cruise', 'Spa for Two'],
        description: 'A week of pure romance — from a luxury overwater villa in the Maldives to private sandbank picnics and starlit dinners. Every moment designed to celebrate your love.',
        itinerary: [
            { day: 1, title: 'Arrival in Paradise', description: 'Seaplane transfer to your overwater villa. Rose petal welcome and champagne toast.', highlights: ['Seaplane transfer', 'Rose petal welcome', 'Champagne toast'] },
            { day: 2, title: 'Private Sandbank Picnic', description: 'Private boat to a secluded sandbank. Gourmet picnic for two surrounded by turquoise waters.', highlights: ['Private boat', 'Sandbank picnic', 'Turquoise lagoon'] },
            { day: 3, title: 'Couples Spa Day', description: 'Full-day spa experience. Side-by-side treatments in the overwater spa pavilion.', highlights: ['Couples massage', 'Overwater spa', 'Aromatherapy'] },
            { day: 4, title: 'Sunset Dolphin Cruise', description: 'Private yacht cruise at sunset. Watch dolphins playing in golden light. Dinner on board.', highlights: ['Dolphin watching', 'Sunset yacht', 'Dinner on board'] },
            { day: 5, title: 'Underwater Adventure', description: 'Couples snorkeling at vibrant coral reefs. Underwater photography session.', highlights: ['Reef snorkeling', 'Underwater photos', 'Marine life'] },
            { day: 6, title: 'Starlit Beach Dinner', description: 'Private dinner on the beach under the stars. Live music and bioluminescent beach walk.', highlights: ['Beach dinner', 'Live music', 'Bioluminescent walk'] },
            { day: 7, title: 'Farewell', description: 'Floating breakfast in your villa. Final moments in paradise before departure.', highlights: ['Floating breakfast', 'Villa memories', 'Departure'] },
        ],
    },
    {
        id: '5',
        slug: 'velora-luxe',
        category: 'luxury',
        title: 'Velora Luxe',
        location: 'Sri Lanka',
        days: 11,
        image_url: '/Photos/Other sections/Sec 2-Luxe-Wellness-Club.jpg',
        tag: 'Luxury',
        highlights: ['Cultural Icons', 'Tea Country', 'Private Safari', 'Coastal Retreats'],
        description: 'Elevated travel through Sri Lanka\'s most refined experiences. Stay at architecturally iconic properties, journey by scenic train through tea estates, enjoy a private Yala safari, and unwind at exclusive coastal retreats. Designed for travellers seeking comfort, privacy, and curated cultural depth.',
        itinerary: [
            { day: 1, title: 'VIP Arrival', description: 'Premium airport welcome. Transfer to a luxury boutique hotel in Colombo. Evening fine dining experience.', highlights: ['VIP clearance', 'Boutique hotel', 'Fine dining'] },
            { day: 2, title: 'Helicopter to the Triangle', description: 'Scenic helicopter transfer to the Cultural Triangle. Check into an iconic resort designed by Geoffrey Bawa.', highlights: ['Helicopter flight', 'Geoffrey Bawa resort', 'Jungle luxury'] },
            { day: 3, title: 'Exclusive Sigiriya', description: 'Private early access to Sigiriya Rock Fortress with an expert historian guide. Afternoon luxury spa treatment.', highlights: ['Exclusive Sigiriya access', 'Historian guide', 'Spa afternoon'] },
            { day: 4, title: 'Kandyan Royalty', description: 'Chauffeured drive to Kandy. Private viewing at the Temple of the Tooth. Stay at a secluded luxury estate.', highlights: ['Chauffeured drive', 'Private temple viewing', 'Luxury estate'] },
            { day: 5, title: 'Tea Country Heights', description: 'Board a private carriage on the scenic train to the tea country. Check into a restored colonial tea planter\'s bungalow.', highlights: ['Private train carriage', 'Colonial bungalow', 'High tea'] },
            { day: 6, title: 'The Planter\'s Life', description: 'Private tea tasting with a master blender. Gourmet picnic lunch amidst the rolling tea fields.', highlights: ['Master tea tasting', 'Gourmet picnic', 'Estate walks'] },
            { day: 7, title: 'Fly to the Wild', description: 'Chartered flight to the south. Arrive at an ultra-luxury tented safari lodge bordering Yala National Park.', highlights: ['Chartered flight', 'Ultra-luxury lodge', 'Wilderness immersion'] },
            { day: 8, title: 'Private Safari Experience', description: 'Exclusive full-day private jeep safari in Yala with a specialized naturalist. Sundowners in the bush.', highlights: ['Private jeep safari', 'Expert naturalist', 'Bush sundowners'] },
            { day: 9, title: 'Coastal Elegance', description: 'Transfer to a premier beachfront resort near Galle. Private villa check-in. Evening at leisure.', highlights: ['Premier beach resort', 'Private villa', 'Ocean views'] },
            { day: 10, title: 'Galle Fort by Night', description: 'Relaxed beach day. Evening private guided tour of Galle Fort followed by a curated chef\'s tasting menu.', highlights: ['Beach relaxation', 'Galle Fort twilight tour', 'Chef\'s tasting menu'] },
            { day: 11, title: 'Luxurious Departure', description: 'Final luxury breakfast. Private transfer to the airport with priority boarding assistance.', highlights: ['Luxury breakfast', 'Private transfer', 'VIP departure'] },
        ],
    },
    {
        id: '6',
        slug: 'maldivian-sunset-escape',
        category: 'honeymoon',
        title: 'Maldivian Sunset Escape',
        location: 'Maldives',
        days: 5,
        image_url: '/images/honeymoon-hero.jpg',
        tag: 'Intimate',
        highlights: ['Beach Villa', 'Private Dinners', 'Couples Yoga'],
        description: 'A short but deeply romantic escape to the Maldives. Perfect for couples who want a concentrated burst of paradise without a long commitment. Every evening ends with a new sunset memory.',
        itinerary: [
            { day: 1, title: 'Arrival & Romance', description: 'Speedboat transfer to your beach villa. Rose petal and candle welcome. Champagne dinner.', highlights: ['Speedboat', 'Rose petal welcome', 'Champagne dinner'] },
            { day: 2, title: 'Reef Adventure', description: 'Private guided snorkeling. Sandbank lunch. Sunset couples yoga.', highlights: ['Snorkeling', 'Sandbank lunch', 'Sunset yoga'] },
            { day: 3, title: 'Spa & Sail', description: 'Balinese couples massage. Afternoon dhoni sailing trip. Dinner on the beach.', highlights: ['Couples massage', 'Dhoni sailing', 'Beach dinner'] },
            { day: 4, title: 'Island Exploration', description: 'Visit a local Maldivian island. Cultural experience. Farewell dinner on a private deck.', highlights: ['Local island', 'Cultural tour', 'Private deck dinner'] },
            { day: 5, title: 'Last Sunrise', description: 'Sunrise meditation for two. Floating breakfast. Departure with memories.', highlights: ['Sunrise meditation', 'Floating breakfast', 'Farewell'] },
        ],
    },

    /* ════════════════════════════════════════
       WELLNESS
       ════════════════════════════════════════ */
    {
        id: '7',
        slug: 'serenity-maldives',
        category: 'wellness',
        title: 'Serenity in the Maldives',
        location: 'Maldives',
        days: 5,
        image_url: '/images/honeymoon-hero.jpg',
        tag: 'Wellness',
        highlights: ['Overwater Spa', 'Sunrise Yoga', 'Wellness Cuisine'],
        description: 'A complete overwater wellness experience — daily spa treatments, yoga at sunrise, and healing nutrition. Strip away stress and reconnect with your inner calm above crystal waters.',
        itinerary: [
            { day: 1, title: 'Arrival & Consultation', description: 'Seaplane to your wellness resort. Personal wellness consultation. Herbal welcome drink.', highlights: ['Seaplane', 'Wellness consultation', 'Herbal welcome'] },
            { day: 2, title: 'Morning Flows', description: 'Sunrise yoga on the overwater deck. Deep tissue massage. Wellness lunch.', highlights: ['Sunrise yoga', 'Deep tissue massage', 'Wellness cuisine'] },
            { day: 3, title: 'Water Healing', description: 'Hydrotherapy session. Ocean swimming meditation. Sound healing at sunset.', highlights: ['Hydrotherapy', 'Ocean meditation', 'Sound healing'] },
            { day: 4, title: 'Mindful Day', description: 'Guided meditation retreat. Ayurvedic facial. Journaling workshop. Star-gazing dinner.', highlights: ['Meditation', 'Ayurvedic facial', 'Star-gazing'] },
            { day: 5, title: 'Renewed Departure', description: 'Final sunrise practice. Wellness summary and take-home programme. Farewell.', highlights: ['Sunrise practice', 'Wellness programme', 'Departure'] },
        ],
    },
    {
        id: '8',
        slug: 'velora-serene',
        category: 'wellness',
        title: 'Velora Serene',
        location: 'Sri Lanka',
        days: 15,
        image_url: '/Photos/Other sections/Destination Tea.jpeg',
        tag: 'Wellness',
        highlights: ['Ayurveda', 'Gentle Exploration', 'Slow Travel'],
        description: 'A restorative journey balancing authentic Ayurveda with light cultural discovery. Enjoy personalised treatments under medical supervision, peaceful countryside settings, early temple visits, and unhurried experiences designed for comfort and calm. Perfect for travellers prioritising wellbeing, slower pacing, and mindful travel.',
        itinerary: [
            { day: 1, title: 'Gentle Arrival', description: 'Personalized airport greeting. Short transfer to a serene wellness resort near Negombo to rest and recalibrate.', highlights: ['Gentle welcome', 'Wellness resort', 'Restorative sleep'] },
            { day: 2, title: 'Consultation & Calm', description: 'Initial consultation with an Ayurvedic doctor. Light yoga and your first restorative massage.', highlights: ['Doctor consultation', 'Light yoga', 'Restorative massage'] },
            { day: 3, title: 'Journey to the Center', description: 'Unhurried drive to the cultural heartland. Check into a nature-immersed retreat surrounded by forest.', highlights: ['Unhurried drive', 'Nature retreat', 'Forest immersion'] },
            { day: 4, title: 'Mindful Heritage', description: 'Morning meditation. A calm, crowd-free visit to the ancient Dambulla Caves. Afternoon herbal steam therapy.', highlights: ['Morning meditation', 'Crowd-free temple', 'Herbal steam'] },
            { day: 5, title: 'Nature Connection', description: 'Gentle nature walk mapping local flora. Afternoon Shirodhara treatment to calm the nervous system.', highlights: ['Nature walk', 'Shirodhara treatment', 'Deep relaxation'] },
            { day: 6, title: 'Ascent to the Hills', description: 'Scenic drive up to Kandy. Visit the tranquil Royal Botanical Gardens. Stay in a quiet highland sanctuary.', highlights: ['Scenic ascent', 'Botanical Gardens', 'Highland sanctuary'] },
            { day: 7, title: 'Sacred Sounds', description: 'Early morning participation in the healing chants at the Temple of the Tooth. Afternoon sound bath session.', highlights: ['Healing chants', 'Sacred temple', 'Sound bath'] },
            { day: 8, title: 'The Healing Mountains', description: 'Travel deeper into the tea country to a specialized wellness estate. Breathe in the pure, cool mountain air.', highlights: ['Wellness estate', 'Mountain air', 'Digital detox'] },
            { day: 9, title: 'Mountain Yoga', description: 'Guided yoga with panoramic mountain views. Learn about the healing properties of Ceylon tea.', highlights: ['Panoramic yoga', 'Tea healing properties', 'Mindful eating'] },
            { day: 10, title: 'Descent to the Sea', description: 'Slow journey down to the southern coast. Arrival at a specialized Ayurvedic beach resort.', highlights: ['Coastal descent', 'Ayurvedic beach resort', 'Ocean air'] },
            { day: 11, title: 'Deep Ayurvedic Healing', description: 'Full day dedicated to your personalized Ayurvedic treatment plan. Dosha-specific meals.', highlights: ['Personalized treatments', 'Dosha meals', 'Healing focus'] },
            { day: 12, title: 'Ocean & Oils', description: 'Morning beach walk. Synchronized Abhyanga massage. Sunset meditation facing the Indian Ocean.', highlights: ['Beach walk', 'Abhyanga massage', 'Sunset meditation'] },
            { day: 13, title: 'Gentle Exploration', description: 'A relaxed afternoon excursion to the historic Galle Fort. Quiet dinner away from the crowds.', highlights: ['Relaxed excursion', 'Galle Fort', 'Quiet dinner'] },
            { day: 14, title: 'Integration', description: 'Final day of treatments. Consultation with the doctor on integrating wellness into your daily life at home.', highlights: ['Final treatments', 'Integration consult', 'Take-home plan'] },
            { day: 15, title: 'Renewed Departure', description: 'Depart feeling completely restored, balanced, and rejuvenated. Transfer to Colombo airport.', highlights: ['Restored energy', 'Balanced state', 'Gentle departure'] },
        ],
    },
    {
        id: '9',
        slug: 'highland-zen-retreat',
        category: 'wellness',
        title: 'Highland Zen Retreat',
        location: 'Sri Lanka',
        days: 6,
        image_url: '/images/tea-plantation.jpg',
        tag: 'Mindfulness',
        highlights: ['Hill Country', 'Meditation', 'Organic Farm'],
        description: 'Escape to the misty highlands of Sri Lanka for a focused mindfulness retreat. Practice yoga among tea plantations, meditate by cascading waterfalls, and nourish yourself with organic farm-to-table cuisine.',
        itinerary: [
            { day: 1, title: 'Mountain Arrival', description: 'Scenic drive to the hill country. Welcome ceremony at the retreat centre. Orientation walk.', highlights: ['Scenic drive', 'Welcome ceremony', 'Orientation'] },
            { day: 2, title: 'Sunrise Practices', description: 'Sunrise yoga overlooking tea fields. Guided meditation by a waterfall. Journaling workshop.', highlights: ['Tea field yoga', 'Waterfall meditation', 'Journaling'] },
            { day: 3, title: 'Farm & Forest', description: 'Visit organic farm. Farm-to-table cooking class. Afternoon forest bathing walk.', highlights: ['Organic farm', 'Cooking class', 'Forest bathing'] },
            { day: 4, title: 'Deep Rest', description: 'Restorative yoga nidra session. Ayurvedic massage. Silent afternoon for reflection.', highlights: ['Yoga nidra', 'Ayurvedic massage', 'Silent reflection'] },
            { day: 5, title: 'Nature Connection', description: 'Hiking through tea plantations. Breathwork session at Little Adams Peak. Community dinner.', highlights: ['Plantation hike', 'Breathwork', 'Community dinner'] },
            { day: 6, title: 'Renewed Departure', description: 'Final sunrise practice. Personalised wellness plan. Transfer to Colombo.', highlights: ['Final practice', 'Wellness plan', 'Transfer'] },
        ],
    },

    /* ════════════════════════════════════════
       ADVENTURE
       ════════════════════════════════════════ */
    {
        id: '10',
        slug: 'serendipity-of-sri-lanka',
        category: 'adventure',
        title: 'Serendipity of Sri Lanka',
        location: 'Sri Lanka',
        days: 8,
        image_url: '/Photos/Other sections/Hill Country.jpg',
        tag: 'Signature',
        highlights: ['Heritage', 'Highlands', 'Wildlife', 'Southern Coast'],
        description: 'A beautifully paced introduction to Sri Lanka\'s iconic highlights. Climb Sigiriya at sunrise, explore sacred Kandy, journey through tea country, enjoy a Yala safari, and unwind along the southern coast. Perfectly balanced for first-time visitors seeking culture, scenery, and relaxation in one seamless journey.',
        itinerary: [
            { day: 1, title: 'Arrival & Negombo', description: 'Welcome to Sri Lanka. Meet your private chauffeur-guide and transfer to your hotel in Negombo.', highlights: ['Airport welcome', 'Coastal relaxation', 'Welcome dinner'] },
            { day: 2, title: 'Into the Cultural Triangle', description: 'Drive to the Cultural Triangle. Visit the ancient Dambulla Cave Temple. Relax at your jungle resort.', highlights: ['Dambulla Cave Temple', 'Jungle resort', 'Cultural immersion'] },
            { day: 3, title: 'Sigiriya & Spice', description: 'Early morning climb of Sigiriya Rock Fortress. Travel to Kandy, stopping at a traditional spice garden en route.', highlights: ['Sigiriya Rock', 'Spice garden tour', 'Arrival in Kandy'] },
            { day: 4, title: 'Sacred Kandy & Tea', description: 'Visit the Temple of the Tooth. Journey up into the misty tea plantations of Nuwara Eliya. Tea factory tour.', highlights: ['Temple of the Tooth', 'Scenic highland drive', 'Tea factory visit'] },
            { day: 5, title: 'Highland Train to Wilderness', description: 'Board the iconic scenic train to Ella. Enjoy the breathtaking views. Meet your driver and continue to Yala.', highlights: ['Scenic train ride', 'Ella mountain views', 'Journey to the wild'] },
            { day: 6, title: 'Yala Safari & Coastal Bound', description: 'Dawn jeep safari in Yala National Park searching for leopards. Travel along the beautiful southern coast to your beach resort.', highlights: ['Yala dawn safari', 'Wildlife spotting', 'Southern coast arrival'] },
            { day: 7, title: 'Galle Fort & Leisure', description: 'Morning guided walk through the UNESCO-listed Galle Fort. Afternoon at leisure on the beach.', highlights: ['Galle Fort tour', 'Colonial history', 'Beach relaxation'] },
            { day: 8, title: 'Departure', description: 'Enjoy your final morning by the ocean before transferring to the airport for your departure flight.', highlights: ['Final beach walk', 'Airport transfer', 'Farewell to Sri Lanka'] },
        ],
    },
    {
        id: '11',
        slug: 'grand-explorer',
        category: 'adventure',
        title: 'Grand Explorer',
        location: 'Sri Lanka',
        days: 20,
        image_url: '/Photos/Other sections/Our Journeys_Classic Discovery.jpeg',
        tag: 'Explorer',
        highlights: ['Ancient Kingdoms', 'Surf Coast', 'Wildlife Safaris', 'Hill Country'],
        description: 'An immersive east-to-south Sri Lankan adventure combining ancient kingdoms, surf coast charm, wildlife safaris, hill country landscapes, and serene beaches. From Sigiriya\'s ancient citadel and Trincomalee\'s turquoise shores to Arugam Bay\'s laid-back coast and Yala\'s leopard territory — this extended journey reveals the island in depth.',
        itinerary: [
            { day: 1, title: 'Arrival & Negombo', description: 'Arrive in Sri Lanka and transfer to a serene coastal resort in Negombo to recover from your flight.', highlights: ['Airport welcome', 'Coastal resort', 'Welcome dinner'] },
            { day: 2, title: 'Journey to the Ancient City', description: 'Travel to the Cultural Triangle. Visit the Dambulla Cave Temple and check into your eco-resort.', highlights: ['Dambulla Cave Temple', 'Scenic drive', 'Eco-resort'] },
            { day: 3, title: 'Sigiriya & Village Life', description: 'Sunrise climb of Sigiriya Rock Fortress. Afternoon traditional village tour with local cooking experience.', highlights: ['Sigiriya Rock', 'Village tour', 'Cooking class'] },
            { day: 4, title: 'Polonnaruwa & Minneriya', description: 'Explore the ancient ruins of Polonnaruwa by bicycle. Afternoon wild elephant safari at Minneriya.', highlights: ['Polonnaruwa ruins', 'Bicycle tour', 'Elephant safari'] },
            { day: 5, title: 'East Coast Bound', description: 'Journey to the pristine east coast of Trincomalee. Check into your beachfront resort.', highlights: ['Cross-country drive', 'Beach resort', 'Ocean views'] },
            { day: 6, title: 'Trincomalee Beaches', description: 'A full day of relaxation on the white sands of Nilaveli beach. Optional snorkeling at Pigeon Island.', highlights: ['Nilaveli beach', 'Pigeon Island', 'Snorkeling'] },
            { day: 7, title: 'Coastal Exploration', description: 'Visit the historic Koneswaram Temple overlooking the ocean. Evening seafood BBQ.', highlights: ['Koneswaram Temple', 'Ocean views', 'Seafood BBQ'] },
            { day: 8, title: 'Surf Coast Journey', description: 'Travel south along the coast to Arugam Bay, Sri Lanka\'s legendary surf destination.', highlights: ['Coastal drive', 'Arugam Bay', 'Surf town vibe'] },
            { day: 9, title: 'Arugam Bay Surf & Sand', description: 'Morning surf lesson or beach relaxation. Afternoon lagoon safari.', highlights: ['Surf lesson', 'Beach time', 'Lagoon safari'] },
            { day: 10, title: 'Into the Highlands', description: 'Leave the coast and ascend into the misty tea country of Ella. Hike to Little Adam\'s Peak.', highlights: ['Highland drive', 'Ella village', 'Little Adam\'s Peak'] },
            { day: 11, title: 'Ella\'s Wonders', description: 'Visit the iconic Nine Arches Bridge. Afternoon hike to Ravana Falls and swim in the natural pools.', highlights: ['Nine Arches Bridge', 'Ravana Falls', 'Mountain air'] },
            { day: 12, title: 'Scenic Train & Tea', description: 'Take the famous scenic train ride to Nuwara Eliya. Visit a working tea factory and taste renowned Ceylon tea.', highlights: ['Scenic train', 'Nuwara Eliya', 'Tea tasting'] },
            { day: 13, title: 'Kandy\'s Sacred Heart', description: 'Descend to Kandy. Visit the Temple of the Sacred Tooth Relic and Royal Botanical Gardens.', highlights: ['Temple of the Tooth', 'Botanical Gardens', 'Kandyan culture'] },
            { day: 14, title: 'Journey to the Wild', description: 'Travel to Yala National Park. Check into a luxury tented camp bordering the wilderness.', highlights: ['Wilderness edge', 'Luxury glamping', 'Campfire dinner'] },
            { day: 15, title: 'Yala Leopard Safari', description: 'Full day safari in Yala National Park, tracking leopards, elephants, and sloth bears.', highlights: ['Leopard tracking', 'Wilderness safari', 'Wildlife photography'] },
            { day: 16, title: 'Southern Shores', description: 'Travel to the palm-fringed southern coast. Check into a boutique beachfront hotel in Tangalle or Mirissa.', highlights: ['Southern coast', 'Boutique hotel', 'Ocean sunset'] },
            { day: 17, title: 'Whale Watching & Galle', description: 'Early morning blue whale watching expedition. Afternoon exploration of the historic Galle Fort.', highlights: ['Whale watching', 'Galle Fort', 'Colonial architecture'] },
            { day: 18, title: 'Coastal Serenity', description: 'A free day to lounge by the pool, enjoy spa treatments, or explore hidden beaches along the coast.', highlights: ['Spa day', 'Beach hopping', 'Relaxation'] },
            { day: 19, title: 'Farewell River Safari', description: 'Morning boat safari on the Madu River mangrove estuary. Final farewell dinner on the beach.', highlights: ['River safari', 'Mangroves', 'Farewell dinner'] },
            { day: 20, title: 'Departure', description: 'Transfer to Colombo International Airport for your journey home, carrying memories of an epic island adventure.', highlights: ['Airport transfer', 'Island memories', 'Onward journey'] },
        ],
    },
    {
        id: '12',
        slug: 'wild-south-expedition',
        category: 'adventure',
        title: 'Wild South Expedition',
        location: 'Sri Lanka',
        days: 7,
        image_url: '/images/safari-wildlife.jpg',
        tag: 'Wildlife',
        highlights: ['Yala Safari', 'Whale Watching', 'Rainforest Trek'],
        description: 'Venture deep into Sri Lanka\'s wild south — leopard safaris at dawn, whale watching at sea, trekking through ancient rainforests, and discovering hidden waterfalls. An adventure lover\'s paradise.',
        itinerary: [
            { day: 1, title: 'Colombo to Sinharaja', description: 'Drive to the Sinharaja Rainforest. Check in to eco lodge. Evening nature walk.', highlights: ['Rainforest drive', 'Eco lodge', 'Nature walk'] },
            { day: 2, title: 'Rainforest Trek', description: 'Full-day guided trek through UNESCO-listed Sinharaja. Spot endemic species. Waterfall swim.', highlights: ['Rainforest trek', 'Endemic species', 'Waterfall'] },
            { day: 3, title: 'Udawalawe Safari', description: 'Elephant safari at Udawalawe National Park. Visit the Elephant Transit Home.', highlights: ['Elephant safari', 'Transit Home', 'Wildlife photography'] },
            { day: 4, title: 'Yala National Park', description: 'Full-day leopard tracking safari at Yala. Luxury safari camp dinner under the stars.', highlights: ['Leopard safari', 'Safari camp', 'Starlit dinner'] },
            { day: 5, title: 'Coastal Adventures', description: 'Travel to the south coast. Stilt fishing experience. Turtle beach visit.', highlights: ['Stilt fishing', 'Turtle beach', 'Coast drive'] },
            { day: 6, title: 'Ocean Giants', description: 'Whale watching off Mirissa. Afternoon in Galle Fort. Farewell seafood dinner.', highlights: ['Whale watching', 'Galle Fort', 'Seafood dinner'] },
            { day: 7, title: 'Departure', description: 'Morning beach walk. Transfer to Colombo airport.', highlights: ['Beach walk', 'Airport transfer', 'Farewell'] },
        ],
    },

    /* ════════════════════════════════════════
       INDIA
       ════════════════════════════════════════ */
    {
        id: '13',
        slug: 'royal-rajasthan',
        category: 'luxury',
        title: 'Royal Rajasthan',
        location: 'India',
        days: 10,
        image_url: '/images/india-jaipur.jpg',
        tag: 'Regal',
        highlights: ['Palace Hotels', 'Desert Safari', 'Taj Mahal'],
        description: 'Live like a maharaja across the golden cities of Rajasthan. Sleep in converted royal palaces, ride camels over sand dunes at sunset, and stand before the Taj Mahal at dawn — India\'s most regal journey awaits.',
        itinerary: [
            { day: 1, title: 'Arrival in Delhi', description: 'VIP arrival at Indira Gandhi International Airport. Transfer to a heritage boutique hotel. Evening Connaught Place dinner.', highlights: ['VIP airport transfer', 'Heritage hotel', 'Delhi welcome dinner'] },
            { day: 2, title: 'Delhi Discovery', description: 'Private tour of Old Delhi — Red Fort, Jama Masjid, Chandni Chowk rickshaw ride. Afternoon Humayun\'s Tomb and Qutb Minar.', highlights: ['Red Fort & Jama Masjid', 'Chandni Chowk', 'Humayun\'s Tomb'] },
            { day: 3, title: 'Taj Mahal Sunrise', description: 'Early train to Agra. Sunrise visit to the Taj Mahal in golden light. Agra Fort exploration. Sunset from Mehtab Bagh across the river.', highlights: ['Taj Mahal at sunrise', 'Agra Fort', 'Mehtab Bagh sunset'] },
            { day: 4, title: 'Jaipur — Pink City Arrival', description: 'Drive through Fatehpur Sikri. Arrive in Jaipur. Check in to a converted 18th-century haveli hotel. Evening bazaar walk.', highlights: ['Fatehpur Sikri', 'Haveli hotel check-in', 'Johari Bazaar'] },
            { day: 5, title: 'Jaipur Palaces', description: 'Amber Fort elephant experience. City Palace museum tour. Hawa Mahal rooftop photography. Rooftop dinner overlooking the Pink City.', highlights: ['Amber Fort', 'City Palace', 'Rooftop dinner'] },
            { day: 6, title: 'Jodhpur — The Blue City', description: 'Drive to Jodhpur. Mehrangarh Fort — one of India\'s mightiest citadels. Stay in a converted royal palace with blue city views.', highlights: ['Mehrangarh Fort', 'Blue city views', 'Palace hotel'] },
            { day: 7, title: 'Desert Village Experience', description: 'Visit Bishnoi villages. Opium ceremony with local chieftain. Traditional Rajasthani lunch. Pottery and weaving demonstrations.', highlights: ['Bishnoi village', 'Cultural ceremony', 'Traditional crafts'] },
            { day: 8, title: 'Jaisalmer — Golden Fort', description: 'Drive to the golden desert city. Jaisalmer Fort tour. Sunset at the Jain temples. Fort hotel dinner.', highlights: ['Jaisalmer Fort', 'Jain Temples', 'Golden sunset'] },
            { day: 9, title: 'Desert Safari', description: 'Camel safari into the Thar Desert dunes. Traditional folk music under the stars. Luxury desert camp night.', highlights: ['Thar Desert camel safari', 'Folk music', 'Luxury desert camp'] },
            { day: 10, title: 'Departure', description: 'Final morning in the desert. Flight back to Delhi for international departure. Farewell gift of Rajasthani handicrafts.', highlights: ['Desert sunrise', 'Delhi flight', 'Farewell hamper'] },
        ],
    },
    {
        id: '14',
        slug: 'kerala-backwaters-soul',
        category: 'wellness',
        title: 'Kerala Backwaters & Soul',
        location: 'India',
        days: 8,
        image_url: '/images/india-kerala.jpg',
        tag: 'Rejuvenate',
        highlights: ['Houseboat Stay', 'Ayurveda Spa', 'Spice Estates'],
        description: 'Glide through Kerala\'s enchanted backwaters on a private houseboat, surrounded by swaying palms and lotus-filled lakes. Combine authentic Ayurvedic treatments with spice estate walks and vibrant Kathakali performances.',
        itinerary: [
            { day: 1, title: 'Arrival in Kochi', description: 'Welcome to God\'s Own Country. Transfer to a heritage hotel in Fort Kochi. Evening Chinese fishing nets at sunset.', highlights: ['Fort Kochi check-in', 'Chinese fishing nets', 'Spice market walk'] },
            { day: 2, title: 'Fort Kochi Exploration', description: 'Jewish Synagogue and Mattancherry Palace tour. Antique shops of Jew Town. Evening Kathakali dance performance.', highlights: ['Jewish Synagogue', 'Mattancherry Palace', 'Kathakali performance'] },
            { day: 3, title: 'Munnar Tea Hills', description: 'Drive to Munnar through spice-scented hills. Tea plantation walk. Eravikulam National Park for Nilgiri Tahr sightings.', highlights: ['Tea plantation', 'Spice garden tour', 'Wildlife sighting'] },
            { day: 4, title: 'Ayurveda Begins', description: 'Arrive at Thekkady wellness retreat. Initial Ayurvedic consultation. First treatment session. Periyar lake sunset cruise.', highlights: ['Wellness retreat', 'Ayurvedic consultation', 'Periyar lake'] },
            { day: 5, title: 'Deep Rejuvenation', description: 'Panchakarma detox treatment. Yoga at sunrise by the lake. Spice estate foraging walk. Evening meditation.', highlights: ['Panchakarma', 'Sunrise yoga', 'Spice estate'] },
            { day: 6, title: 'Houseboat Journey', description: 'Board your own private luxury houseboat at Alleppey. Glide through palm-fringed waterways. Seafood Kerala feast on board.', highlights: ['Private houseboat', 'Backwater canals', 'Fresh seafood'] },
            { day: 7, title: 'Backwater Bliss', description: 'Morning village stops along the waterways. Watch traditional boat races. Sunset from the roof deck. Star-gazing over the lake.', highlights: ['Village visits', 'Boat race viewing', 'Sunset deck'] },
            { day: 8, title: 'Departure', description: 'Disembark at Alleppey. Transfer to Kochi for international departure. Take-home Ayurvedic wellness kit.', highlights: ['Disembark', 'Kochi transfer', 'Wellness kit farewell gift'] },
        ],
    },
    {
        id: '15',
        slug: 'golden-triangle-discovery',
        category: 'adventure',
        title: 'Golden Triangle Discovery',
        location: 'India',
        days: 7,
        image_url: '/images/india-taj.jpg',
        tag: 'Heritage',
        highlights: ['Taj Mahal', 'Jaipur Forts', 'Delhi Heritage'],
        description: 'India\'s legendary Golden Triangle — Delhi, Agra, and Jaipur — packed into a perfectly paced 7-day adventure. Stand before the Taj Mahal at sunrise, explore the mighty forts of Rajasthan, and lose yourself in the chaos and colour of Old Delhi.',
        itinerary: [
            { day: 1, title: 'Delhi Arrival', description: 'Private airport welcome. Heritage hotel in Lutyens\' Delhi. Evening India Gate walk and Rajpath boulevard.', highlights: ['Airport transfer', 'Heritage hotel', 'India Gate'] },
            { day: 2, title: 'Old & New Delhi', description: 'Red Fort, Jama Masjid, and Chandni Chowk by morning. Lotus Temple and Qutb Minar in the afternoon. Rooftop dinner.', highlights: ['Red Fort', 'Chandni Chowk', 'Qutb Minar'] },
            { day: 3, title: 'Taj Mahal at Sunrise', description: 'Pre-dawn train to Agra. First entry to the Taj Mahal complex at sunrise. Agra Fort. Return to Delhi by evening.', highlights: ['Taj Mahal sunrise', 'Agra Fort', 'Express train'] },
            { day: 4, title: 'Drive to Jaipur', description: 'Scenic drive to the Pink City via Fatehpur Sikri — the abandoned Mughal city. Jaipur city welcome dinner.', highlights: ['Fatehpur Sikri', 'Pink City arrival', 'Welcome dinner'] },
            { day: 5, title: 'Amber Fort', description: 'Amber Fort elephant ride (optional). City Palace. Jantar Mantar astronomical observatory. Bazaar shopping.', highlights: ['Amber Fort', 'City Palace', 'Jantar Mantar'] },
            { day: 6, title: 'Jaipur Highlights', description: 'Hawa Mahal photography at dawn. Nahargarh Fort sunset. Traditional Rajasthani thali dinner. Puppet show.', highlights: ['Hawa Mahal', 'Nahargarh Fort', 'Rajasthani dinner'] },
            { day: 7, title: 'Departure', description: 'Morning at leisure in Jaipur. Drive or fly back to Delhi. International departure.', highlights: ['Final morning', 'Delhi transfer', 'Departure'] },
        ],
    },
];

export const journeys: Journey[] = [
    {
        id: 'culture',
        title: 'Culture',
        subtitle: 'Ancient Wonders Await',
        description: 'Walk through centuries of history among sacred temples, towering rock fortresses, and vibrant festivals. From the ruins of Polonnaruwa to the sacred tooth relic of Kandy.',
        image: '/images/safari-wildlife.jpg',
        color: 'from-amber-600/80 to-orange-900/80',
    },
    {
        id: 'relaxation',
        title: 'Relaxation',
        subtitle: 'Serenity Redefined',
        description: 'Surrender to crystal lagoons, overwater villas, and world-class spas. Let the rhythm of the Indian Ocean wash away the world as you find your perfect state of bliss.',
        image: '/images/wellness-hero.jpg',
        color: 'from-cyan-600/80 to-blue-900/80',
    },
    {
        id: 'adventure',
        title: 'Adventure',
        subtitle: 'Thrills Beyond Borders',
        description: 'Dive with manta rays, trek misty peaks, and ride the world\'s most scenic train. Every day brings a new frontier of excitement across two extraordinary destinations.',
        image: '/images/tea-plantation.jpg',
        color: 'from-emerald-600/80 to-teal-900/80',
    },
];

export const heroSlides = [
    {
        image: '/images/coastline.jpg',
        title: 'Uncover the Soul of Sri Lanka',
        subtitle: '& The Heart of the Maldives',
    },
    {
        image: '/images/temple.jpg',
        title: 'Where Ancient Temples',
        subtitle: 'Meet Crystal Waters',
    },
    {
        image: '/images/sigiriya.jpg',
        title: 'Luxury Beyond',
        subtitle: 'Imagination',
    },
    {
        image: '/images/india-jaipur.jpg',
        title: 'Royal Palaces &',
        subtitle: 'Timeless Wonders',
    },
];

/* ── Helpers ── */
export function getPackagesByCategory(category: string): Package[] {
    return packages.filter((p) => p.category === category);
}

export function getPackageBySlug(category: string, slug: string): Package | undefined {
    return packages.find((p) => p.category === category && p.slug === slug);
}
