import { Package, Journey } from './types';

export const packages: Package[] = [
    /* ════════════════════════════════════════
       LUXURY
       ════════════════════════════════════════ */
    {
        id: '1',
        slug: 'azure-atoll-escape',
        category: 'luxury',
        title: 'Azure Atoll Escape',

        location: 'Maldives',
        days: 5,
        image_url: '/images/maldives-beach.jpg',
        tag: 'Luxury',
        highlights: ['Overwater Villa', 'Seaplane Transfer', 'Private Dining'],
        description: 'Surrender to the unparalleled luxury of the Maldivian atolls. Your private overwater villa awaits above crystal-clear lagoons, where dolphin pods play at dawn and bioluminescent plankton illuminate the night.',
        itinerary: [
            { day: 1, title: 'Seaplane to Paradise', description: 'Arrive at Velana International Airport. Board a scenic seaplane to your private atoll resort. Welcome with champagne on the jetty of your overwater villa.', highlights: ['Seaplane transfer', 'Overwater villa check-in', 'Champagne welcome'] },
            { day: 2, title: 'Ocean Discovery', description: 'Guided snorkeling at the house reef. Afternoon private catamaran cruise with dolphin spotting. Sunset dining on a private sandbank.', highlights: ['House reef snorkeling', 'Dolphin cruise', 'Sandbank dinner'] },
            { day: 3, title: 'Underwater Wonders', description: 'Visit the resort\'s marine biology center. Guided diving excursion to a pristine coral wall. Evening underwater restaurant experience.', highlights: ['Marine biology tour', 'Coral wall diving', 'Underwater dining'] },
            { day: 4, title: 'Spa & Serenity', description: 'Full-day overwater spa journey. Traditional Maldivian healing ritual. Private yoga session at sunrise. Bioluminescent beach walk at night.', highlights: ['Overwater spa treatment', 'Sunrise yoga', 'Bioluminescent beach'] },
            { day: 5, title: 'Fond Farewell', description: 'Final sunrise from your villa deck. Gourmet farewell breakfast. Seaplane transfer back to Malé with lasting memories of paradise.', highlights: ['Villa sunrise', 'Farewell breakfast', 'Seaplane departure'] },
        ],
    },
    {
        id: '2',
        slug: 'the-dual-paradise',
        category: 'luxury',
        title: 'The Dual Paradise',
        location: 'Sri Lanka & Maldives',
        days: 14,
        image_url: '/images/luxury-hero.jpg',
        tag: 'Signature',
        highlights: ['Two Destinations', 'Heritage & Beach', 'Overwater Spa'],
        description: 'The ultimate journey combining the cultural richness of Sri Lanka with the pristine luxury of the Maldives. Seven days immersed in ancient temples, misty mountains, and wildlife safaris, followed by seven days of overwater bliss.',
        itinerary: [
            { day: 1, title: 'Colombo Arrival', description: 'Welcome to Sri Lanka. VIP airport pickup and transfer to your boutique heritage hotel. Evening Colombo food tour.', highlights: ['VIP airport transfer', 'Heritage hotel', 'Colombo food tour'] },
            { day: 2, title: 'Cultural Triangle', description: 'Journey to Sigiriya. Visit Dambulla Golden Temple. Check in to your private villa overlooking the ancient rock fortress.', highlights: ['Dambulla Golden Temple', 'Private villa', 'Sigiriya views'] },
            { day: 3, title: 'Sigiriya & Safari', description: 'Early climb of Sigiriya Rock. Afternoon jeep safari at Minneriya National Park for the elephant gathering.', highlights: ['Sigiriya Rock climb', 'Minneriya safari', 'Elephant gathering'] },
            { day: 4, title: 'Kandy Heritage', description: 'Travel to Kandy through spice gardens. Visit Temple of the Tooth. Private Kandyan dance performance.', highlights: ['Spice gardens', 'Temple of the Tooth', 'Dance performance'] },
            { day: 5, title: 'Tea Plantations', description: 'Full-day tea country exploration. Visit Ceylon Tea Museum. Private estate lunch in the highlands.', highlights: ['Tea Museum', 'Plantation walk', 'Highland lunch'] },
            { day: 6, title: 'Ella & Nine Arches', description: 'Scenic train ride to Ella. Visit the iconic Nine Arches Bridge. Ella Rock sunset hike.', highlights: ['Scenic train ride', 'Nine Arches Bridge', 'Sunset hike'] },
            { day: 7, title: 'Southern Coast', description: 'Travel to the southern coast. Visit Galle Fort. Sunset whale watching excursion off Mirissa.', highlights: ['Galle Fort', 'Beach resort', 'Whale watching'] },
            { day: 8, title: 'Fly to Maldives', description: 'Morning flight from Colombo to Malé. Seaplane transfer to your luxury overwater villa. Welcome ceremony.', highlights: ['Flight to Malé', 'Seaplane transfer', 'Overwater villa'] },
            { day: 9, title: 'Reef Discovery', description: 'Guided house reef snorkeling with marine biologist. Afternoon spa treatment. Private beach cinema under the stars.', highlights: ['Reef snorkeling', 'Spa treatment', 'Beach cinema'] },
            { day: 10, title: 'Deep Blue Adventure', description: 'Half-day diving expedition to Manta Ray Point. Jet ski excursion. Floating breakfast in your villa.', highlights: ['Manta ray diving', 'Jet skiing', 'Floating breakfast'] },
            { day: 11, title: 'Island Exploration', description: 'Private yacht trip to uninhabited islands. Picnic lunch on a pristine sandbar. Sunset fishing with local fishermen.', highlights: ['Private yacht', 'Sandbar picnic', 'Sunset fishing'] },
            { day: 12, title: 'Wellness Day', description: 'Full-day Maldivian wellness journey. Overwater spa rituals. Sunrise yoga and meditation. Star-gazing dinner.', highlights: ['Wellness rituals', 'Yoga & meditation', 'Star-gazing dinner'] },
            { day: 13, title: 'Ocean Freedom', description: 'Free day to explore at your leisure. Parasailing, paddleboarding, or simply relax. Chef\'s farewell dinner.', highlights: ['Water sports', 'Relaxation', 'Chef\'s farewell dinner'] },
            { day: 14, title: 'Paradise Farewell', description: 'Final sunrise meditation. Farewell brunch overlooking the lagoon. Seaplane transfer and departure.', highlights: ['Sunrise meditation', 'Farewell brunch', 'Seaplane departure'] },
        ],
    },
    {
        id: '3',
        slug: 'golden-coast-retreat',
        category: 'luxury',
        title: 'Golden Coast Retreat',
        location: 'Sri Lanka',
        days: 7,
        image_url: '/images/wellness-hero.jpg',
        tag: 'Premium',
        highlights: ['Boutique Hotels', 'Galle Fort', 'Private Chef'],
        description: 'Experience Sri Lanka\'s stunning southern coastline from handpicked boutique hotels. Explore the colonial charm of Galle Fort, surf pristine waves, and dine with a private chef on moonlit beaches.',
        itinerary: [
            { day: 1, title: 'Welcome to the Coast', description: 'Arrive in Colombo and transfer to your beachfront boutique hotel on the southern coast.', highlights: ['Airport transfer', 'Beachfront check-in', 'Welcome cocktail'] },
            { day: 2, title: 'Galle Fort Exploration', description: 'Private guided tour of the UNESCO-listed Galle Fort. Artisan shopping and colonial architecture.', highlights: ['Galle Fort tour', 'Artisan boutiques', 'Fort rooftop dining'] },
            { day: 3, title: 'Whale Watching', description: 'Early morning whale watching expedition off Mirissa. Afternoon at leisure on the beach.', highlights: ['Blue whale spotting', 'Beach relaxation', 'Seafood dinner'] },
            { day: 4, title: 'Surfing & Beach Life', description: 'Morning surf lesson at Weligama Bay. Afternoon spa treatment. Private beach dinner.', highlights: ['Surf lesson', 'Spa treatment', 'Beach dinner'] },
            { day: 5, title: 'Tea Country Day Trip', description: 'Scenic drive through tea plantations. Visit a boutique tea estate. Afternoon tea tasting.', highlights: ['Tea plantations', 'Estate visit', 'Tea tasting'] },
            { day: 6, title: 'Jungle & Lagoon', description: 'Kayak through mangrove lagoons. Visit a turtle hatchery. Evening private chef dinner.', highlights: ['Mangrove kayaking', 'Turtle hatchery', 'Private chef'] },
            { day: 7, title: 'Departure', description: 'Final morning yoga on the beach. Transfer to Colombo airport.', highlights: ['Beach yoga', 'Airport transfer', 'Farewell gift'] },
        ],
    },

    /* ════════════════════════════════════════
       HONEYMOON
       ════════════════════════════════════════ */
    {
        id: '4',
        slug: 'island-romance',
        category: 'honeymoon',
        title: 'Island Romance',
        location: 'Maldives',
        days: 7,
        image_url: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1200&q=80',
        tag: 'Romance',
        highlights: ['Overwater Villa', 'Sunset Cruise', 'Spa for Two'],
        description: 'A week of pure romance — from a luxury overwater villa in the Maldives to private sandbank picnics and starlit dinners. Every moment designed to celebrate your love.',
        itinerary: [
            { day: 1, title: 'Arrival in Paradise', description: 'Seaplane transfer to your overwater villa. Rose petal welcome and champagne toast.', highlights: ['Seaplane transfer', 'Rose petal welcome', 'Champagne toast'] },
            { day: 2, title: 'Private Sandbank Picnic', description: 'Private boat to a secluded sandbank. Gourmet picnic for two surrounded by turquoise waters.', highlights: ['Private boat', 'Sandbank picnic', 'Turquoise lagoon'] },
            { day: 3, title: 'Couples Spa Day', description: 'Full-day spa experience. Side-by-side treatments in the overwater spa pavilion.', highlights: ['Couples massage', 'Overwater spa', 'Aromatherapy'] },
            { day: 4, title: 'Sunset Dolphin Cruise', description: 'Private yacht cruise at sunset. Watch dolphins playing in golden light. Dinner on board.', highlights: ['Dolphin watching', 'Sunset yacht', 'Dinner on board'] },
            { day: 5, title: 'Underwater Adventure', description: 'Couples snorkeling at vibrant coral reefs. Underwater photography session.', highlights: ['Reef snorkeling', 'Underwater photos', 'Marine life'] },
            { day: 6, title: 'Starlit Beach Dinner', description: 'Private dinner on the beach under the stars. Live music and bioluminescent beach walk.', highlights: ['Beach dinner', 'Live music', 'Bioluminescent walk'] },
            { day: 7, title: 'Farewell', description: 'Floating breakfast in your villa. Final moments in paradise before departure.', highlights: ['Floating breakfast', 'Villa memories', 'Departure'] },
        ],
    },
    {
        id: '5',
        slug: 'heritage-ocean-honeymoon',
        category: 'honeymoon',
        title: 'Heritage & Ocean Honeymoon',
        location: 'Sri Lanka & Maldives',
        days: 12,
        image_url: 'https://images.unsplash.com/photo-1602002418816-5c0aeef426aa?w=1200&q=80',
        tag: 'Duo',
        highlights: ['Sri Lanka & Maldives', 'Boutique Hotels', 'Private Experiences'],
        description: 'Begin with the cultural magic of Sri Lanka — misty highlands, ancient temples, and tea plantations — then unwind in a Maldivian paradise. The perfect blend of adventure and relaxation for newlyweds.',
        itinerary: [
            { day: 1, title: 'Colombo Welcome', description: 'VIP airport transfer. Check in to a heritage boutique hotel. Romantic welcome dinner.', highlights: ['VIP transfer', 'Heritage hotel', 'Welcome dinner'] },
            { day: 2, title: 'City of Gems', description: 'Private gemstone shopping tour. Visit the Colombo National Museum. Rooftop dinner.', highlights: ['Gemstone tour', 'National Museum', 'Rooftop dining'] },
            { day: 3, title: 'Kandy Romance', description: 'Journey to Kandy. Temple of the Tooth visit. Couples spa at luxury lakeside hotel.', highlights: ['Kandy drive', 'Temple visit', 'Lakeside spa'] },
            { day: 4, title: 'Tea Country', description: 'Scenic drive through plantations. Private tea tasting. Dinner at a colonial-era estate.', highlights: ['Tea plantations', 'Tea tasting', 'Estate dinner'] },
            { day: 5, title: 'Ella Magic', description: 'Iconic train ride to Ella. Nine Arches Bridge at golden hour. Hilltop boutique stay.', highlights: ['Train ride', 'Nine Arches Bridge', 'Boutique hotel'] },
            { day: 6, title: 'Southern Coast', description: 'Travel to the coast. Explore Galle Fort hand in hand. Beach sunset.', highlights: ['Galle Fort', 'Beach walk', 'Sunset cocktails'] },
            { day: 7, title: 'Fly to Maldives', description: 'Morning flight to Malé. Seaplane to your private resort. Overwater villa check-in.', highlights: ['Flight', 'Seaplane', 'Overwater villa'] },
            { day: 8, title: 'Ocean Bliss', description: 'Snorkeling together at the house reef. Private cooking class with resort chef.', highlights: ['Snorkeling', 'Cooking class', 'Private dining'] },
            { day: 9, title: 'Spa & Sailing', description: 'Couples spa morning. Afternoon private catamaran sailing. Sunset champagne.', highlights: ['Couples spa', 'Catamaran sail', 'Sunset champagne'] },
            { day: 10, title: 'Sandbank Escape', description: 'Boat to a private sandbank. Gourmet picnic. Afternoon at leisure.', highlights: ['Sandbank', 'Gourmet picnic', 'Leisure time'] },
            { day: 11, title: 'Beach Cinema Night', description: 'Free day for water sports or relaxation. Private beach cinema under the stars.', highlights: ['Water sports', 'Beach cinema', 'Star gazing'] },
            { day: 12, title: 'Farewell Paradise', description: 'Floating breakfast. Farewell photography. Transfer to Malé.', highlights: ['Floating breakfast', 'Photography', 'Departure'] },
        ],
    },
    {
        id: '6',
        slug: 'maldivian-sunset-escape',
        category: 'honeymoon',
        title: 'Maldivian Sunset Escape',
        location: 'Maldives',
        days: 5,
        image_url: '/images/honeymoon-hero.jpg',
        tag: 'Intimate',
        highlights: ['Beach Villa', 'Private Dinners', 'Couples Yoga'],
        description: 'A short but deeply romantic escape to the Maldives. Perfect for couples who want a concentrated burst of paradise without a long commitment. Every evening ends with a new sunset memory.',
        itinerary: [
            { day: 1, title: 'Arrival & Romance', description: 'Speedboat transfer to your beach villa. Rose petal and candle welcome. Champagne dinner.', highlights: ['Speedboat', 'Rose petal welcome', 'Champagne dinner'] },
            { day: 2, title: 'Reef Adventure', description: 'Private guided snorkeling. Sandbank lunch. Sunset couples yoga.', highlights: ['Snorkeling', 'Sandbank lunch', 'Sunset yoga'] },
            { day: 3, title: 'Spa & Sail', description: 'Balinese couples massage. Afternoon dhoni sailing trip. Dinner on the beach.', highlights: ['Couples massage', 'Dhoni sailing', 'Beach dinner'] },
            { day: 4, title: 'Island Exploration', description: 'Visit a local Maldivian island. Cultural experience. Farewell dinner on a private deck.', highlights: ['Local island', 'Cultural tour', 'Private deck dinner'] },
            { day: 5, title: 'Last Sunrise', description: 'Sunrise meditation for two. Floating breakfast. Departure with memories.', highlights: ['Sunrise meditation', 'Floating breakfast', 'Farewell'] },
        ],
    },

    /* ════════════════════════════════════════
       WELLNESS
       ════════════════════════════════════════ */
    {
        id: '7',
        slug: 'serenity-maldives',
        category: 'wellness',
        title: 'Serenity in the Maldives',
        location: 'Maldives',
        days: 5,
        image_url: '/images/honeymoon-hero.jpg',
        tag: 'Wellness',
        highlights: ['Overwater Spa', 'Sunrise Yoga', 'Wellness Cuisine'],
        description: 'A complete overwater wellness experience — daily spa treatments, yoga at sunrise, and healing nutrition. Strip away stress and reconnect with your inner calm above crystal waters.',
        itinerary: [
            { day: 1, title: 'Arrival & Consultation', description: 'Seaplane to your wellness resort. Personal wellness consultation. Herbal welcome drink.', highlights: ['Seaplane', 'Wellness consultation', 'Herbal welcome'] },
            { day: 2, title: 'Morning Flows', description: 'Sunrise yoga on the overwater deck. Deep tissue massage. Wellness lunch.', highlights: ['Sunrise yoga', 'Deep tissue massage', 'Wellness cuisine'] },
            { day: 3, title: 'Water Healing', description: 'Hydrotherapy session. Ocean swimming meditation. Sound healing at sunset.', highlights: ['Hydrotherapy', 'Ocean meditation', 'Sound healing'] },
            { day: 4, title: 'Mindful Day', description: 'Guided meditation retreat. Ayurvedic facial. Journaling workshop. Star-gazing dinner.', highlights: ['Meditation', 'Ayurvedic facial', 'Star-gazing'] },
            { day: 5, title: 'Renewed Departure', description: 'Final sunrise practice. Wellness summary and take-home programme. Farewell.', highlights: ['Sunrise practice', 'Wellness programme', 'Departure'] },
        ],
    },
    {
        id: '8',
        slug: 'ayurveda-beach-retreat',
        category: 'wellness',
        title: 'Ayurveda & Beach Retreat',
        location: 'Sri Lanka',
        days: 10,
        image_url: '/images/wellness-hero.jpg',
        tag: 'Healing',
        highlights: ['Ayurvedic Programme', 'Tea Plantations', 'Coastal Retreat'],
        description: 'Begin with a traditional Ayurvedic programme in Sri Lanka\'s hill country — herbal treatments, meditation, and yoga — then transition to beachside relaxation on the southern coast.',
        itinerary: [
            { day: 1, title: 'Colombo Arrival', description: 'Airport transfer. Check in to wellness centre. Initial Ayurvedic consultation with resident doctor.', highlights: ['Airport transfer', 'Wellness centre', 'Doctor consultation'] },
            { day: 2, title: 'Ayurvedic Beginning', description: 'Morning yoga. First Ayurvedic treatment session. Dosha-balancing meals throughout the day.', highlights: ['Yoga', 'Ayurvedic treatment', 'Dosha meals'] },
            { day: 3, title: 'Deep Treatment', description: 'Shirodhara oil therapy. Herbal steam bath. Guided nature walk through tea country.', highlights: ['Shirodhara', 'Herbal steam', 'Nature walk'] },
            { day: 4, title: 'Mountain Wellness', description: 'Sunrise meditation in the highlands. Abhyanga massage. Tea plantation visit.', highlights: ['Mountain meditation', 'Abhyanga massage', 'Tea visit'] },
            { day: 5, title: 'Yoga Intensive', description: 'Extended yoga session. Pranayama breathing workshop. Cooking class with Ayurvedic recipes.', highlights: ['Yoga intensive', 'Pranayama', 'Cooking class'] },
            { day: 6, title: 'Journey South', description: 'Travel to the southern coast. Check in to beachfront resort. Oceanside meditation.', highlights: ['Coastal transfer', 'Beach resort', 'Ocean meditation'] },
            { day: 7, title: 'Ocean Therapy', description: 'Beach yoga at sunrise. Sea salt body scrub. Afternoon swimming and relaxation.', highlights: ['Beach yoga', 'Body scrub', 'Swimming'] },
            { day: 8, title: 'Spa & Sea', description: 'Hot stone massage. Aloe vera wrap. Stand-up paddle boarding at sunset.', highlights: ['Hot stone massage', 'Aloe wrap', 'Paddle boarding'] },
            { day: 9, title: 'Mindful Closing', description: 'Final meditation session. Wellness review with practitioner. Farewell beach dinner.', highlights: ['Final meditation', 'Wellness review', 'Beach dinner'] },
            { day: 10, title: 'Departure', description: 'Gentle morning stretch. Transfer to Colombo airport with personalised wellness plan.', highlights: ['Morning stretch', 'Wellness plan', 'Departure'] },
        ],
    },
    {
        id: '9',
        slug: 'highland-zen-retreat',
        category: 'wellness',
        title: 'Highland Zen Retreat',
        location: 'Sri Lanka',
        days: 6,
        image_url: '/images/tea-plantation.jpg',
        tag: 'Mindfulness',
        highlights: ['Hill Country', 'Meditation', 'Organic Farm'],
        description: 'Escape to the misty highlands of Sri Lanka for a focused mindfulness retreat. Practice yoga among tea plantations, meditate by cascading waterfalls, and nourish yourself with organic farm-to-table cuisine.',
        itinerary: [
            { day: 1, title: 'Mountain Arrival', description: 'Scenic drive to the hill country. Welcome ceremony at the retreat centre. Orientation walk.', highlights: ['Scenic drive', 'Welcome ceremony', 'Orientation'] },
            { day: 2, title: 'Sunrise Practices', description: 'Sunrise yoga overlooking tea fields. Guided meditation by a waterfall. Journaling workshop.', highlights: ['Tea field yoga', 'Waterfall meditation', 'Journaling'] },
            { day: 3, title: 'Farm & Forest', description: 'Visit organic farm. Farm-to-table cooking class. Afternoon forest bathing walk.', highlights: ['Organic farm', 'Cooking class', 'Forest bathing'] },
            { day: 4, title: 'Deep Rest', description: 'Restorative yoga nidra session. Ayurvedic massage. Silent afternoon for reflection.', highlights: ['Yoga nidra', 'Ayurvedic massage', 'Silent reflection'] },
            { day: 5, title: 'Nature Connection', description: 'Hiking through tea plantations. Breathwork session at Little Adams Peak. Community dinner.', highlights: ['Plantation hike', 'Breathwork', 'Community dinner'] },
            { day: 6, title: 'Renewed Departure', description: 'Final sunrise practice. Personalised wellness plan. Transfer to Colombo.', highlights: ['Final practice', 'Wellness plan', 'Transfer'] },
        ],
    },

    /* ════════════════════════════════════════
       ADVENTURE
       ════════════════════════════════════════ */
    {
        id: '10',
        slug: 'royal-ceylon-odyssey',
        category: 'adventure',
        title: 'Royal Ceylon Odyssey',
        location: 'Sri Lanka',
        days: 10,
        image_url: '/images/sigiriya.jpg',
        tag: 'Heritage',
        highlights: ['Sigiriya', 'Kandy', 'Ella Train', 'Wildlife Safari'],
        description: 'Embark on a majestic journey through the ancient heart of Sri Lanka. From the towering rock fortress of Sigiriya to the sacred temples of Kandy and the misty tea plantations of Ella, this odyssey weaves together centuries of royal history with breathtaking natural beauty.',
        itinerary: [
            { day: 1, title: 'Arrival in Colombo', description: 'Welcome to the Pearl of the Indian Ocean. Private airport transfer to your luxury hotel. Evening sunset cocktails at Galle Face Green.', highlights: ['Airport VIP transfer', 'Galle Face Hotel check-in', 'Welcome dinner with local cuisine'] },
            { day: 2, title: 'Colombo City Discovery', description: 'Explore the vibrant capital with a private guide. Visit Gangaramaya Temple, wander through Pettah Market, and dine at Ministry of Crab.', highlights: ['Private city tour', 'Gangaramaya Temple', 'Fine dining experience'] },
            { day: 3, title: 'Journey to Sigiriya', description: 'Travel to the Cultural Triangle. Visit Dambulla Cave Temple en route. Afternoon at leisure at your eco-luxury resort overlooking Sigiriya Rock.', highlights: ['Dambulla Cave Temple', 'Scenic drive through countryside', 'Eco-resort check-in'] },
            { day: 4, title: 'Sigiriya Rock Fortress', description: 'Early morning climb of the legendary Lion Rock fortress. Explore the ancient frescoes and marvel at the engineering of a 5th-century sky palace.', highlights: ['Sigiriya sunrise climb', 'Ancient frescoes', 'Royal gardens tour'] },
            { day: 5, title: 'Minneriya & Polonnaruwa', description: 'Morning safari at Minneriya National Park to witness the famous elephant gathering. Afternoon exploration of the ancient city of Polonnaruwa.', highlights: ['Elephant safari', 'Polonnaruwa ruins', 'Ancient Buddhist sculptures'] },
            { day: 6, title: 'Sacred Kandy', description: 'Travel to the hill capital of Kandy. Visit the Temple of the Sacred Tooth Relic. Evening Kandyan dance performance.', highlights: ['Temple of the Tooth', 'Kandyan dance show', 'Lakeside luxury hotel'] },
            { day: 7, title: 'Tea Country Experience', description: 'Journey through lush tea plantations. Visit a working tea factory. Private tea-tasting session with a master blender.', highlights: ['Tea plantation tour', 'Factory visit', 'Master tea tasting'] },
            { day: 8, title: 'Train to Ella', description: 'Board the iconic blue train for one of the world\'s most scenic railway journeys. Arrive in charming Ella surrounded by misty mountains.', highlights: ['Iconic train journey', 'Nine Arches Bridge', 'Mountain village charm'] },
            { day: 9, title: 'Ella Adventures', description: 'Hike to Little Adam\'s Peak for panoramic views. Visit Ravana Falls. Afternoon cooking class learning authentic Sri Lankan recipes.', highlights: ['Little Adam\'s Peak trek', 'Ravana Falls', 'Cooking class'] },
            { day: 10, title: 'Farewell Departure', description: 'Final morning at leisure. Private transfer to Bandaranaike International Airport. Depart with unforgettable memories.', highlights: ['Leisurely breakfast', 'Airport transfer', 'Farewell gift hamper'] },
        ],
    },
    {
        id: '11',
        slug: 'explorers-dual-paradise',
        category: 'adventure',
        title: "Explorer's Dual Paradise",
        location: 'Sri Lanka & Maldives',
        days: 14,
        image_url: 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=1200&q=80',
        tag: 'Epic',
        highlights: ['Sri Lanka & Maldives', 'Diving', 'Heritage Tours', 'Safari'],
        description: 'The ultimate adventure — cultural Sri Lanka combined with underwater exploration in the Maldives. From 5th-century fortresses to world-class dive sites, this journey is for those who crave both history and adrenaline.',
        itinerary: [
            { day: 1, title: 'Colombo Landing', description: 'Arrive in Sri Lanka. Private transfer to boutique hotel. Evening street food walking tour.', highlights: ['Private transfer', 'Boutique hotel', 'Street food tour'] },
            { day: 2, title: 'Negombo & Fishing', description: 'Visit Negombo fish market at dawn. Afternoon lagoon kayaking. Dutch Canal exploration.', highlights: ['Fish market', 'Kayaking', 'Dutch Canal'] },
            { day: 3, title: 'Wilderness Safari', description: 'Drive to Yala National Park. Morning leopard safari. Luxury glamping under the stars.', highlights: ['Yala safari', 'Leopard tracking', 'Glamping'] },
            { day: 4, title: 'Sigiriya Climb', description: 'Sunrise climb of Lion Rock. Explore royal water gardens. Village bicycle tour.', highlights: ['Sigiriya Rock', 'Water gardens', 'Bicycle tour'] },
            { day: 5, title: 'Knuckles Range Trek', description: 'Guided hiking through the Knuckles Mountain Range. Waterfall swimming. Local village homestay dinner.', highlights: ['Mountain trek', 'Waterfall swim', 'Village dinner'] },
            { day: 6, title: 'Kandy to Ella Train', description: 'Board the scenic train. Nine Arches Bridge. Evening at a mountain lodge.', highlights: ['Scenic train', 'Nine Arches', 'Mountain lodge'] },
            { day: 7, title: 'White Water & Coast', description: 'Morning white-water rafting in Kitulgala. Drive to the southern coast. Beach sunset.', highlights: ['White-water rafting', 'Beach arrival', 'Sunset'] },
            { day: 8, title: 'Fly to Maldives', description: 'Morning flight to Malé. Speedboat to dive resort. Afternoon reef check dive.', highlights: ['Flight', 'Dive resort', 'Check dive'] },
            { day: 9, title: 'Manta Point', description: 'Morning dive at Manta Ray Point. Afternoon free diving lesson. Night snorkeling.', highlights: ['Manta rays', 'Free diving', 'Night snorkel'] },
            { day: 10, title: 'Shipwreck Dive', description: 'Explore a sunken shipwreck. Underwater photography session. Island BBQ dinner.', highlights: ['Shipwreck', 'Underwater photos', 'Island BBQ'] },
            { day: 11, title: 'Shark Safari', description: 'Nurse shark snorkeling excursion. Visit local fishing island. Cultural exchange.', highlights: ['Shark snorkel', 'Local island', 'Cultural exchange'] },
            { day: 12, title: 'Coral Garden', description: 'Drift dive through pristine coral gardens. Afternoon sandbank picnic. Bioluminescent walk.', highlights: ['Coral dive', 'Sandbank', 'Bioluminescence'] },
            { day: 13, title: 'Freedom Day', description: 'Choose your adventure: kayaking, parasailing, or relaxation. Chef\'s farewell dinner.', highlights: ['Free choice', 'Water sports', 'Farewell dinner'] },
            { day: 14, title: 'Departure', description: 'Final ocean sunrise. Transfer to Malé for departure.', highlights: ['Ocean sunrise', 'Transfer', 'Farewell'] },
        ],
    },
    {
        id: '12',
        slug: 'wild-south-expedition',
        category: 'adventure',
        title: 'Wild South Expedition',
        location: 'Sri Lanka',
        days: 7,
        image_url: '/images/safari-wildlife.jpg',
        tag: 'Wildlife',
        highlights: ['Yala Safari', 'Whale Watching', 'Rainforest Trek'],
        description: 'Venture deep into Sri Lanka\'s wild south — leopard safaris at dawn, whale watching at sea, trekking through ancient rainforests, and discovering hidden waterfalls. An adventure lover\'s paradise.',
        itinerary: [
            { day: 1, title: 'Colombo to Sinharaja', description: 'Drive to the Sinharaja Rainforest. Check in to eco lodge. Evening nature walk.', highlights: ['Rainforest drive', 'Eco lodge', 'Nature walk'] },
            { day: 2, title: 'Rainforest Trek', description: 'Full-day guided trek through UNESCO-listed Sinharaja. Spot endemic species. Waterfall swim.', highlights: ['Rainforest trek', 'Endemic species', 'Waterfall'] },
            { day: 3, title: 'Udawalawe Safari', description: 'Elephant safari at Udawalawe National Park. Visit the Elephant Transit Home.', highlights: ['Elephant safari', 'Transit Home', 'Wildlife photography'] },
            { day: 4, title: 'Yala National Park', description: 'Full-day leopard tracking safari at Yala. Luxury safari camp dinner under the stars.', highlights: ['Leopard safari', 'Safari camp', 'Starlit dinner'] },
            { day: 5, title: 'Coastal Adventures', description: 'Travel to the south coast. Stilt fishing experience. Turtle beach visit.', highlights: ['Stilt fishing', 'Turtle beach', 'Coast drive'] },
            { day: 6, title: 'Ocean Giants', description: 'Whale watching off Mirissa. Afternoon in Galle Fort. Farewell seafood dinner.', highlights: ['Whale watching', 'Galle Fort', 'Seafood dinner'] },
            { day: 7, title: 'Departure', description: 'Morning beach walk. Transfer to Colombo airport.', highlights: ['Beach walk', 'Airport transfer', 'Farewell'] },
        ],
    },

    /* ════════════════════════════════════════
       INDIA
       ════════════════════════════════════════ */
    {
        id: '13',
        slug: 'royal-rajasthan',
        category: 'luxury',
        title: 'Royal Rajasthan',
        location: 'India',
        days: 10,
        image_url: '/images/india-jaipur.jpg',
        tag: 'Regal',
        highlights: ['Palace Hotels', 'Desert Safari', 'Taj Mahal'],
        description: 'Live like a maharaja across the golden cities of Rajasthan. Sleep in converted royal palaces, ride camels over sand dunes at sunset, and stand before the Taj Mahal at dawn — India\'s most regal journey awaits.',
        itinerary: [
            { day: 1, title: 'Arrival in Delhi', description: 'VIP arrival at Indira Gandhi International Airport. Transfer to a heritage boutique hotel. Evening Connaught Place dinner.', highlights: ['VIP airport transfer', 'Heritage hotel', 'Delhi welcome dinner'] },
            { day: 2, title: 'Delhi Discovery', description: 'Private tour of Old Delhi — Red Fort, Jama Masjid, Chandni Chowk rickshaw ride. Afternoon Humayun\'s Tomb and Qutb Minar.', highlights: ['Red Fort & Jama Masjid', 'Chandni Chowk', 'Humayun\'s Tomb'] },
            { day: 3, title: 'Taj Mahal Sunrise', description: 'Early train to Agra. Sunrise visit to the Taj Mahal in golden light. Agra Fort exploration. Sunset from Mehtab Bagh across the river.', highlights: ['Taj Mahal at sunrise', 'Agra Fort', 'Mehtab Bagh sunset'] },
            { day: 4, title: 'Jaipur — Pink City Arrival', description: 'Drive through Fatehpur Sikri. Arrive in Jaipur. Check in to a converted 18th-century haveli hotel. Evening bazaar walk.', highlights: ['Fatehpur Sikri', 'Haveli hotel check-in', 'Johari Bazaar'] },
            { day: 5, title: 'Jaipur Palaces', description: 'Amber Fort elephant experience. City Palace museum tour. Hawa Mahal rooftop photography. Rooftop dinner overlooking the Pink City.', highlights: ['Amber Fort', 'City Palace', 'Rooftop dinner'] },
            { day: 6, title: 'Jodhpur — The Blue City', description: 'Drive to Jodhpur. Mehrangarh Fort — one of India\'s mightiest citadels. Stay in a converted royal palace with blue city views.', highlights: ['Mehrangarh Fort', 'Blue city views', 'Palace hotel'] },
            { day: 7, title: 'Desert Village Experience', description: 'Visit Bishnoi villages. Opium ceremony with local chieftain. Traditional Rajasthani lunch. Pottery and weaving demonstrations.', highlights: ['Bishnoi village', 'Cultural ceremony', 'Traditional crafts'] },
            { day: 8, title: 'Jaisalmer — Golden Fort', description: 'Drive to the golden desert city. Jaisalmer Fort tour. Sunset at the Jain temples. Fort hotel dinner.', highlights: ['Jaisalmer Fort', 'Jain Temples', 'Golden sunset'] },
            { day: 9, title: 'Desert Safari', description: 'Camel safari into the Thar Desert dunes. Traditional folk music under the stars. Luxury desert camp night.', highlights: ['Thar Desert camel safari', 'Folk music', 'Luxury desert camp'] },
            { day: 10, title: 'Departure', description: 'Final morning in the desert. Flight back to Delhi for international departure. Farewell gift of Rajasthani handicrafts.', highlights: ['Desert sunrise', 'Delhi flight', 'Farewell hamper'] },
        ],
    },
    {
        id: '14',
        slug: 'kerala-backwaters-soul',
        category: 'wellness',
        title: 'Kerala Backwaters & Soul',
        location: 'India',
        days: 8,
        image_url: '/images/india-kerala.jpg',
        tag: 'Rejuvenate',
        highlights: ['Houseboat Stay', 'Ayurveda Spa', 'Spice Estates'],
        description: 'Glide through Kerala\'s enchanted backwaters on a private houseboat, surrounded by swaying palms and lotus-filled lakes. Combine authentic Ayurvedic treatments with spice estate walks and vibrant Kathakali performances.',
        itinerary: [
            { day: 1, title: 'Arrival in Kochi', description: 'Welcome to God\'s Own Country. Transfer to a heritage hotel in Fort Kochi. Evening Chinese fishing nets at sunset.', highlights: ['Fort Kochi check-in', 'Chinese fishing nets', 'Spice market walk'] },
            { day: 2, title: 'Fort Kochi Exploration', description: 'Jewish Synagogue and Mattancherry Palace tour. Antique shops of Jew Town. Evening Kathakali dance performance.', highlights: ['Jewish Synagogue', 'Mattancherry Palace', 'Kathakali performance'] },
            { day: 3, title: 'Munnar Tea Hills', description: 'Drive to Munnar through spice-scented hills. Tea plantation walk. Eravikulam National Park for Nilgiri Tahr sightings.', highlights: ['Tea plantation', 'Spice garden tour', 'Wildlife sighting'] },
            { day: 4, title: 'Ayurveda Begins', description: 'Arrive at Thekkady wellness retreat. Initial Ayurvedic consultation. First treatment session. Periyar lake sunset cruise.', highlights: ['Wellness retreat', 'Ayurvedic consultation', 'Periyar lake'] },
            { day: 5, title: 'Deep Rejuvenation', description: 'Panchakarma detox treatment. Yoga at sunrise by the lake. Spice estate foraging walk. Evening meditation.', highlights: ['Panchakarma', 'Sunrise yoga', 'Spice estate'] },
            { day: 6, title: 'Houseboat Journey', description: 'Board your own private luxury houseboat at Alleppey. Glide through palm-fringed waterways. Seafood Kerala feast on board.', highlights: ['Private houseboat', 'Backwater canals', 'Fresh seafood'] },
            { day: 7, title: 'Backwater Bliss', description: 'Morning village stops along the waterways. Watch traditional boat races. Sunset from the roof deck. Star-gazing over the lake.', highlights: ['Village visits', 'Boat race viewing', 'Sunset deck'] },
            { day: 8, title: 'Departure', description: 'Disembark at Alleppey. Transfer to Kochi for international departure. Take-home Ayurvedic wellness kit.', highlights: ['Disembark', 'Kochi transfer', 'Wellness kit farewell gift'] },
        ],
    },
    {
        id: '15',
        slug: 'golden-triangle-discovery',
        category: 'adventure',
        title: 'Golden Triangle Discovery',
        location: 'India',
        days: 7,
        image_url: '/images/india-taj.jpg',
        tag: 'Heritage',
        highlights: ['Taj Mahal', 'Jaipur Forts', 'Delhi Heritage'],
        description: 'India\'s legendary Golden Triangle — Delhi, Agra, and Jaipur — packed into a perfectly paced 7-day adventure. Stand before the Taj Mahal at sunrise, explore the mighty forts of Rajasthan, and lose yourself in the chaos and colour of Old Delhi.',
        itinerary: [
            { day: 1, title: 'Delhi Arrival', description: 'Private airport welcome. Heritage hotel in Lutyens\' Delhi. Evening India Gate walk and Rajpath boulevard.', highlights: ['Airport transfer', 'Heritage hotel', 'India Gate'] },
            { day: 2, title: 'Old & New Delhi', description: 'Red Fort, Jama Masjid, and Chandni Chowk by morning. Lotus Temple and Qutb Minar in the afternoon. Rooftop dinner.', highlights: ['Red Fort', 'Chandni Chowk', 'Qutb Minar'] },
            { day: 3, title: 'Taj Mahal at Sunrise', description: 'Pre-dawn train to Agra. First entry to the Taj Mahal complex at sunrise. Agra Fort. Return to Delhi by evening.', highlights: ['Taj Mahal sunrise', 'Agra Fort', 'Express train'] },
            { day: 4, title: 'Drive to Jaipur', description: 'Scenic drive to the Pink City via Fatehpur Sikri — the abandoned Mughal city. Jaipur city welcome dinner.', highlights: ['Fatehpur Sikri', 'Pink City arrival', 'Welcome dinner'] },
            { day: 5, title: 'Amber Fort', description: 'Amber Fort elephant ride (optional). City Palace. Jantar Mantar astronomical observatory. Bazaar shopping.', highlights: ['Amber Fort', 'City Palace', 'Jantar Mantar'] },
            { day: 6, title: 'Jaipur Highlights', description: 'Hawa Mahal photography at dawn. Nahargarh Fort sunset. Traditional Rajasthani thali dinner. Puppet show.', highlights: ['Hawa Mahal', 'Nahargarh Fort', 'Rajasthani dinner'] },
            { day: 7, title: 'Departure', description: 'Morning at leisure in Jaipur. Drive or fly back to Delhi. International departure.', highlights: ['Final morning', 'Delhi transfer', 'Departure'] },
        ],
    },
];

export const journeys: Journey[] = [
    {
        id: 'culture',
        title: 'Culture',
        subtitle: 'Ancient Wonders Await',
        description: 'Walk through centuries of history among sacred temples, towering rock fortresses, and vibrant festivals. From the ruins of Polonnaruwa to the sacred tooth relic of Kandy.',
        image: '/images/safari-wildlife.jpg',
        color: 'from-amber-600/80 to-orange-900/80',
    },
    {
        id: 'relaxation',
        title: 'Relaxation',
        subtitle: 'Serenity Redefined',
        description: 'Surrender to crystal lagoons, overwater villas, and world-class spas. Let the rhythm of the Indian Ocean wash away the world as you find your perfect state of bliss.',
        image: '/images/wellness-hero.jpg',
        color: 'from-cyan-600/80 to-blue-900/80',
    },
    {
        id: 'adventure',
        title: 'Adventure',
        subtitle: 'Thrills Beyond Borders',
        description: 'Dive with manta rays, trek misty peaks, and ride the world\'s most scenic train. Every day brings a new frontier of excitement across two extraordinary destinations.',
        image: '/images/tea-plantation.jpg',
        color: 'from-emerald-600/80 to-teal-900/80',
    },
];

export const heroSlides = [
    {
        image: '/images/coastline.jpg',
        title: 'Uncover the Soul of Sri Lanka',
        subtitle: '& The Heart of the Maldives',
    },
    {
        image: '/images/temple.jpg',
        title: 'Where Ancient Temples',
        subtitle: 'Meet Crystal Waters',
    },
    {
        image: '/images/sigiriya.jpg',
        title: 'Luxury Beyond',
        subtitle: 'Imagination',
    },
    {
        image: '/images/india-jaipur.jpg',
        title: 'Royal Palaces &',
        subtitle: 'Timeless Wonders',
    },
];

/* ── Helpers ── */
export function getPackagesByCategory(category: string): Package[] {
    return packages.filter((p) => p.category === category);
}

export function getPackageBySlug(category: string, slug: string): Package | undefined {
    return packages.find((p) => p.category === category && p.slug === slug);
}
